# ExecutePVSAnalyzer.cmake
# ─────────────────────────────────────────────────────────────────────────────
# Creates a custom target `pvs_analysis` that runs PVS-Studio static analysis
# on the compile_commands.json generated by CMake.
#
# Prerequisites:
#   - include(cmake/FindPVSExecutable.cmake) and find_PVS_executable() must
#     have been called first, setting PVS_ANALYZER_EXECUTABLE and
#     PVS_LOG_CONVERTER_EXECUTABLE.
#   - CMAKE_EXPORT_COMPILE_COMMANDS must be ON.
#
# Run with:  cmake --build <dir> --target pvs_analysis
# ─────────────────────────────────────────────────────────────────────────────
include_guard(GLOBAL)

function(add_pvs_analysis_target)
  if(NOT PVS_ANALYZER_EXECUTABLE OR NOT PVS_LOG_CONVERTER_EXECUTABLE)
    message(WARNING "[PVS] Analyser executables not set — skipping target")
    return()
  endif()

  set(_compile_db   "${CMAKE_BINARY_DIR}/compile_commands.json")
  set(_report_log   "${CMAKE_BINARY_DIR}/pvs_report.log")
  set(_report_json  "${CMAKE_BINARY_DIR}/pvs_report.json")
  set(_exclude_dir  "${PROJECT_SOURCE_DIR}/test")

  # Resolve the PVS-Studio licence path
  if(WIN32)
    set(_license "$ENV{APPDATA}/PVS-Studio/Settings.xml")
  else()
    set(_license "$ENV{HOME}/.config/PVS-Studio/PVS-Studio.lic")
  endif()

  add_custom_target(pvs_analysis
    COMMENT "[PVS] Running PVS-Studio static analysis..."
    # Step 1 — analyse
    COMMAND "${PVS_ANALYZER_EXECUTABLE}"
      analyze
      -f "${_compile_db}"
      -l "${_license}"
      -o "${_report_log}"
      -e "${_exclude_dir}"
      -j2
    # Step 2 — convert log to JSON
    COMMAND "${PVS_LOG_CONVERTER_EXECUTABLE}"
      -a GA:1,2
      -t json
      -o "${_report_json}"
      "${_report_log}"
    WORKING_DIRECTORY "${CMAKE_BINARY_DIR}"
    VERBATIM
  )

  message(STATUS "[PVS] Target 'pvs_analysis' created (run: cmake --build <dir> --target pvs_analysis)")
endfunction()
